project:
  type: book

book:
  title: "Desarrollo_Web"
  author: "T.S. Christopher Jara"
  date: "2025-18-09"
  chapters:
    - index.qmd
    - 1_intro.qmd
    - part: "El Uso de Visual Studio Code"
      Chapters:
        - 2_Visual_Studio_Code.qmd
        - 3_Instalación de Visual estudio Code.qmd
        - 4_Configuración_Visual_Studio_Code.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

publish:
  type: gitHub
  method: branch
  repository: https://github.com/profechrisjara/DesarrolloWeb_2025.git
  branch: gh-pages
  pre-render: true



